# Frank's Docker Configuration for milk (https://github.com/markoshust/docker-magento)
# Version 21.1.1

version: "3"

services:
  app:
    image: milk/nginx:v1.0
    ports:
      - "89:8000"
    links:
      - redis
      - phpfpm
    volumes: &appvolumes
      - ~/.composer:/var/www/.composer
      - appdata:/var/www/html
      - sockdata:/sock

  phpfpm:
    image: milk/php-fpm:v1.0
    links:
      - redis
    volumes: *appvolumes

  redis:
    image: redis
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6380:6379"
    volumes:
      - redisdata:/data
volumes:
  appdata:
  redisdata:
  sockdata:
